server:
  port: 6001

spring:
  application:
    name: sean-eureka-server

eureka:  instance:    hostname: localhost
  client:    register-with-eureka: false #服务器注册，false表示不将自己注册到Eureka服务中
    fetch-registry: false #服务发现，false表示自己不从Eureka中获取注册信息
    service-url:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/