server:
  port: 7001

spring:
  application:
    name: sean-gateway-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

zuul:  sensitive-headers: null #不屏蔽Cookie,Authorization
  add-host-header: true
  routes:    authentication: 
      path: /auth/**
      service-id: SEAN-SECURITY-SERVER
      strip-prefix: false
    product: 
      path: /product/**
      service-id: SEAN-RESOURCE-PRODUCT
      strip-prefix: false