server:
  port: 80

spring:
  application:
    name: sean-resource-product
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true